// Compact, generated state per project: brain/projects/<slug>/STATE.md. Code only, no model call.
// Borrowed from Alfred: a projection is generated from the records and never read back as the authority. The owner
// edits project.json / SUMMARY / plan; this file only gathers them, links the supporting records, and keeps confirmed
// facts apart from assumptions and inferred (learned) preferences. Rewritten only when its inputs change.
import fs from "node:fs";
import path from "node:path";
import { PROJECTS, writeText, localStamp } from "./store.ts";
import * as brain from "./brain.ts";
import * as preferences from "./preferences.ts";

/** What the orchestrator knows that the brain files don't: live work, briefs, questions, linked signals. */
export type Inputs = {
  work: { project: string | null; title: string; status: string; kind: "task" | "plan" | "question"; detail?: string }[];
  assumptions: { project: string | null; text: string; from: string }[];
  signals: { project: string | null; at: string; source: string; title: string; why: string }[];
};
let lastSig = "", lastAt = 0;

export function render(slug: string, inp: Inputs): string | null {
  const p = brain.getProject(slug); if (!p) return null;
  const now = new Date();
  const decisions = brain.recentDecisions(5, slug);
  const goals = brain.listGoals().filter(g => g.project === slug);
  const openSteps = goals.flatMap(g => g.steps.filter(st => !st.done).map(st => ({ g, st })));
  const blockedSteps = openSteps.filter(({ g, st }) => (st.dependsOn || []).some(id => !g.steps.find(x => x.id === id)?.done));
  const reminders = brain.listReminders().filter(r => !r.done && r.project === slug).sort((a, b) => +brain.whenToDate(a.due) - +brain.whenToDate(b.due)).slice(0, 6);
  const milestones = brain.listMilestones().filter(m => !m.done && m.project === slug && m.date >= now.toISOString().slice(0, 10)).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 6);
  const work = inp.work.filter(w => w.project === slug), assum = inp.assumptions.filter(a => a.project === slug).slice(0, 8), sig = inp.signals.filter(s => s.project === slug).slice(0, 6);
  const learned = preferences.list().filter(x => x.scope === "project" && x.project === slug && preferences.isLearned(x)).slice(0, 5);
  let reports: string[] = []; try { reports = fs.readdirSync(path.join(PROJECTS, slug, "reports")).filter(f => f.endsWith(".md")).sort().reverse().slice(0, 4); } catch {}
  const L = (h: string, rows: string[], empty = "") => rows.length ? [`## ${h}`, ...rows, ""] : empty ? [`## ${h}`, empty, ""] : [];
  return [
    `# ${p.name}: current state`,
    `_Generated by HQ ${localStamp(now)} from the brain records. Don't edit: change project.json, SUMMARY.md, plan.md or decisions instead._`, "",
    "## Objective (confirmed)", `- ${p.summary || "(no summary)"}`, `- Stage: ${p.stage || "?"} · health: ${p.health || "?"}`, `- Next step: ${p.nextStep || "(not set)"}`, "",
    ...L("Recent decisions (confirmed, decisions.md)", decisions.map(d => `- ${d.replace(/\s+/g, " ").slice(0, 240)}`)),
    ...L("Active work (live)", work.map(w => `- [${w.kind}] ${w.title}: ${w.status}${w.detail ? ` · ${w.detail}` : ""}`), "- Nothing running."),
    ...L("Dependencies", blockedSteps.map(({ g, st }) => `- "${st.title}" (${g.title}) waits for: ${(st.dependsOn || []).map(id => g.steps.find(x => x.id === id)?.title || id).join(", ")}`)),
    ...L("Next actions", [p.nextStep ? `- ${p.nextStep}` : "", ...openSteps.filter(x => !blockedSteps.includes(x)).slice(0, 4).map(({ g, st }) => `- ${st.title} (goal: ${g.title})`)].filter(Boolean)),
    ...L("Dates", [...milestones.map(m => `- ${m.date.slice(0, 10)} · ${m.title}`), ...reminders.map(r => `- ${brain.whenToDate(r.due).toISOString().slice(0, 16).replace("T", " ")} · reminder: ${r.title}`)]),
    ...L("Linked signals (mail/calendar, matched by HQ)", sig.map(s => `- ${s.at.slice(0, 10)} · ${s.source}: ${s.title} (${s.why})`)),
    ...L("Sources", [...(p.paths || []).map(x => `- folder: ${x}`), ...(p.repos || []).map(x => `- repo: ${x}`), ...(p.links || []).map(l => `- ${l.label}: ${l.url}`), ...reports.map(r => `- report: reports/${r}`)]),
    ...L("Assumptions (not confirmed by the owner)", assum.map(a => `- ${a.text} (from ${a.from})`)),
    ...L("Inferred preferences (learned, not stated)", learned.map(x => `- ${x.text}`)),
  ].join("\n");
}

/** Rewrites changed STATE.md files, at most every 2 minutes. Returns how many changed. */
export function refresh(inputs: () => Inputs, force = false): number {
  if (!force && Date.now() - lastAt < 120e3) return 0;
  lastAt = Date.now();
  const inp = inputs(), sig = JSON.stringify([inp, brain.listProjects().map(p => [p.slug, p.updated, p.nextStep, p.stage, p.health]), brain.listReminders().length, brain.listMilestones().length, brain.recentDecisions(3)]);
  if (!force && sig === lastSig) return 0;
  lastSig = sig;
  let n = 0;
  for (const p of brain.listProjects()) {
    const text = render(p.slug, inp); if (!text) continue;
    const f = path.join(PROJECTS, p.slug, "STATE.md");
    let cur = ""; try { cur = fs.readFileSync(f, "utf8"); } catch {}
    if (cur.replace(/^_Generated by HQ [^\n]*\n/m, "") === text.replace(/^_Generated by HQ [^\n]*\n/m, "")) continue;
    writeText(f, text); n++;
  }
  return n;
}
